const bookTitles = [
  "2001: A Space Odyssey",
  "A Bend in the River",
  "A Boy’s Own Story",
  "A Christmas Carol",
  "A Clockwork Orange",
  "A Dance to the Music of Time",
  "A Day in Spring",
  "A Day Off",
  "A Disaffection",
  "A Dream of Red Mansions",
  "A Dry White Season",
  "A Farewell to Arms",
  "A Fine Balance",
  "A Ghost at Noon",
  "A Handful of Dust",
  "A Heart So White",
  "A Hero of Our Times",
  "A Home at the End of the World",
  "A Kestrel for a Knave",
  "A Light Comedy",
  "A Maggot",
  "A Man Asleep",
  "A Modest Proposal",
  "A Pale View of Hills",
  "A Passage to India",
  "A Portrait of the Artist as a Young Man",
  "A Prayer for Owen Meany",
  "A Question of Power",
  "A Room With a View",
  "A Scots Quair (Sunset Song)",
  "A Sentimental Journey",
  "A Severed Head",
  "A Short History of Tractors in Ukrainian",
  "A Suitable Boy",
  "A Tale of a Tub",
  "A Tale of Love and Darkness",
  "A Tale of Two Cities",
  "A Thousand Cranes",
  "A Town Like Alice",
  "A Void/Avoid",
  "A Woman’s Life",
  "A World for Julius",
  "A World of Love",
  "Aaron’s Rod",
  "Absalom, Absalom!",
  "Absolute Beginners",
  "Ada",
  "Adam Bede",
  "Adjunct: An Undigest",
  "Aesop’s Fables",
  "After the Death of Don Juan",
  "After the Quake",
  "Against the Day",
  "Against the Grain",
  "Agnes Grey",
  "Aithiopika",
  "Alamut",
  "Albert Angelo",
  "Alberta and Jacob",
  "Alias Grace",
  "Alice’s Adventures in Wonderland",
  "All About H. Hatterr",
  "All Quiet on the Western Front",
  "All Souls",
  "All Souls Day",
  "All the Pretty Horses",
  "Almost Transparent Blue",
  "Amadis of Gaul",
  "Amateurs",
  "Amelia",
  "American Pastoral",
  "American Psycho",
  "Amerika",
  "Amok",
  "Amongst Women",
  "Amsterdam",
  "An Artist of the Floating World",
  "An Obedient Father",
  "Anagrams",
  "Ancestral Voices",
  "Andrea",
  "Animal Farm",
  "Animal's People",
  "Anna Karenina",
  "Annie John",
  "Another World",
  "Antic Hay",
  "Anton Reiser",
  "Arcadia",
  "Arcanum 17",
  "Around the World in Eighty Days",
  "Arrow of God",
  "As a Man Grows Older",
  "As If I Am Not There",
  "Ashes and Diamonds",
  "Asphodel",
  "Astradeni",
  "At Swim-Two-Birds",
  "At Swim, Two Boys",
  "At the Mountains of Madness",
  "Atonement",
  "August is a Wicked Month",
  "Austerlitz",
  "Auto-da-Fé",
  "Autumn of the Patriarch",
  "Babbitt",
  "Back",
  "Back to Oegstgeest",
  "Baltasar and Blimunda",
  "Barabbas",
  "Bartleby and Co.",
  "Bebo's Girl",
  "Before Night Falls",
  "Bel-Ami",
  "Belle du Seigneur",
  "Beloved",
  "Ben-Hur",
  "Berlin Alexanderplatz",
  "Between the Acts",
  "Billiards at Half-Past Nine",
  "Billy Bathgate",
  "Billy Budd, Foretopman",
  "Billy Liar",
  "Birdsong",
  "Black Box",
  "Black Dogs",
  "Black Water",
  "Blaming",
  "Bleak House",
  "Blind Man With a Pistol",
  "Blindness",
  "Blonde",
  "Blood and Guts in High School",
  "Blood Meridian",
  "Blue of Noon",
  "Bonjour Tristesse",
  "Born in Exile",
  "Borstal Boy",
  "Bosnian Chronicle",
  "Bouvard and Pécuchet",
  "Brave New World",
  "Breakfast at Tiffany’s",
  "Breakfast of Champions",
  "Brideshead Revisited",
  "Brighton Rock",
  "Broad and Aliens is the World",
  "Broken April",
  "Buddenbrooks",
  "Bunner Sisters",
  "Burger’s Daughter",
  "Burmese Days",
  "By the Open Sea",
  "Cakes and Ale",
  "Call it Sleep",
  "Camera Obscura",
  "Camilla",
  "Cancer Ward",
  "Candide",
  "Cane",
  "Cannery Row",
  "Captain Corelli’s Mandolin",
  "Carry Me Down",
  "Casino Royale",
  "Castle Rackrent",
  "Castle Richmond",
  "Cat and Mouse",
  "Cat’s Cradle",
  "Cat’s Eye",
  "Cataract",
  "Catch-22",
  "Caught",
  "Cause for Alarm",
  "Cecilia",
  "Celestial Harmonies",
  "Chaireas and Kallirhoe",
  "Chaka the Zulu",
  "Cheese",
  "Chess Story",
  "Chocky",
  "Choke",
  "Christ Stopped at Eboli",
  "Cider With Rosie",
  "Cigarettes",
  "City of God",
  "City Primeval",
  "City Sister Silver",
  "Clarissa",
  "Claudine's House",
  "Clear Light of Day",
  "Closely Watched Trains",
  "Cloud Atlas",
  "Cloudsplitter",
  "Cocaine Nights",
  "Cold Comfort Farm",
  "Come Back, Dr. Caligari",
  "Coming Up for Air",
  "Compassion",
  "Complicity",
  "Concrete",
  "Confederacy of Dunces",
  "Confessions",
  "Contact",
  "Conversations In Sicily",
  "Correction",
  "Couples, Passerby",
  "Cranford",
  "Crash",
  "Crime and Punishment",
  "Crome Yellow",
  "Crossfire",
  "Cry, the Beloved Country",
  "Cryptonomicon",
  "Cutter and Bone",
  "Dangerous Liaisons",
  "Dangling Man",
  "Daniel Deronda",
  "Dark as the Grave Wherein My Friend is Laid",
  "David Copperfield",
  "Day of the Dolphin",
  "Day of the Triffids",
  "Dead Air",
  "Dead Babies",
  "Dead Souls",
  "Death and the Dervish",
  "Death in Rome",
  "Death in Venice",
  "Death Sentence",
  "Decline and Fall",
  "Deep River",
  "Deep Rivers",
  "Delta of Venus",
  "Democracy",
  "Diary of a Nobody",
  "Dictionary of the Khazars",
  "Dining on Stones",
  "Dirk Gently’s Holistic Detective Agency",
  "Dirty Havana Trilogy",
  "Disappearance",
  "Disgrace",
  "Disobedience",
  "Dispatches",
  "Do Androids Dream of Electric Sheep?",
  "Doctor Faustus",
  "Doctor Zhivago",
  "Dog Years",
  "Dom Casmurro",
  "Don Quixote",
  "Don’t Move",
  "Down Second Avenue",
  "Down There",
  "Downriver",
  "Dracula",
  "Drop City",
  "Drunkard",
  "Dusklands",
  "Eclipse of the Crescent Moon",
  "Elective Affinities",
  "Elementary Particles",
  "Eline Vere",
  "Elizabeth Costello",
  "Embers",
  "Emma",
  "Empire of the Sun",
  "Enduring Love",
  "England Made Me",
  "Enigma of Arrival",
  "Erewhon",
  "Ethan Frome",
  "Eugene Onegin",
  "Eugénie Grandet",
  "Euphues: The Anatomy of Wit",
  "Eva Trout",
  "Evelina",
  "Everything is Illuminated",
  "Everything That Rises Must Converge",
  "Everything You Need",
  "Excellent Women",
  "Exercises in Style",
  "Extinction",
  "Eyeless in Gaza",
  "Faceless Killers",
  "Faces in the Water",
  "Facundo",
  "Fado Alexandrino",
  "Fall on Your Knees",
  "Falling Man",
  "Family Matters",
  "Fanny Hill",
  "Fantômas",
  "Far from the Madding Crowd",
  "Farewell My Lovely",
  "Fateless",
  "Fathers and Sons",
  "Fear and Loathing in Las Vegas",
  "Fear and Trembling",
  "Fear of Flying",
  "Felicia’s Journey",
  "Ferdydurke",
  "Ficciones",
  "Fifth Business",
  "Fingersmith",
  "Finnegans Wake",
  "Flaubert’s Parrot",
  "Foe",
  "Fool's Gold",
  "Fools of Fortune",
  "For Whom the Bell Tolls",
  "Forever a Stranger",
  "Fortunata and Jacinta",
  "Foucault’s Pendulum",
  "Foundation",
  "Frankenstein",
  "Franny and Zooey",
  "Froth on the Daydream",
  "Fruits of the Earth",
  "Fugitive Pieces",
  "Fury",
  "G",
  "Gabriel’s Gift",
  "Gabriela, Clove and Cinnamon",
  "Garden, Ashes",
  "Gargantua and Pantagruel",
  "Germinal",
  "Get Shorty",
  "Giles Goat-Boy",
  "Gimmick!",
  "Giovanni’s Room",
  "Girl With Green Eyes",
  "Glamorama",
  "Go Down, Moses",
  "Go Tell It on the Mountain",
  "Goalie’s Anxiety at the Penalty Kick",
  "God Bless You, Mr. Rosewater",
  "God's Bits of Wood",
  "Gone With the Wind",
  "Good Morning, Midnight",
  "Goodbye to Berlin",
  "Gormenghast",
  "Gösta Berling’s Saga",
  "Gravity’s Rainbow",
  "Great Apes",
  "Great Expectations",
  "Green Henry",
  "Grimus",
  "Group Portrait With Lady",
  "Growth of the Soil",
  "Gulliver’s Travels",
  "Hadrian the Seventh",
  "Half of a Yellow Sun",
  "Half of Man is Woman",
  "Halftime",
  "Hallucinating Foucault",
  "Hangover Square",
  "Hard Times",
  "Harriet Hume",
  "Hawksmoor",
  "He Knew He Was Right",
  "Heart of Darkness",
  "Heartbreak Tango",
  "Hebdomeros",
  "Henderson the Rain King",
  "Henry of Ofterdingen",
  "Her Privates We",
  "Here's to You, Jesusa",
  "Herzog",
  "Hideous Kinky",
  "High Rise",
  "Home and the World",
  "Homo Faber",
  "House in the Uplands",
  "House Mother Normal",
  "House of Leaves",
  "How It Is",
  "How Late It Was, How Late",
  "How the Dead Live",
  "Howards End",
  "Humboldt’s Gift",
  "Humphrey Clinker",
  "Hunger",
  "Hyperion",
  "I Know Why the Caged Bird Sings",
  "I Thought of Daisy",
  "I, Robot",
  "I'm Not Scared",
  "I’m Not Stiller",
  "If Not Now, When?",
  "If On a Winter’s Night a Traveler",
  "If This Is a Man",
  "Ignorance",
  "Impressions of Africa",
  "In A Free State",
  "In a Glass Darkly",
  "In Cold Blood",
  "In Parenthesis",
  "In Search of Klingsor",
  "In the Forest",
  "In the Heart of the Country",
  "In The Heart of the Seas",
  "In Watermelon Sugar",
  "Independent People",
  "Indian Summer",
  "Indigo",
  "Infinite Jest",
  "Inland",
  "Inside Mr. Enderby",
  "Interview With the Vampire",
  "Intimacy",
  "Invisible Cities",
  "Invisible Man",
  "Islands",
  "Ivanhoe",
  "Jack Maggs",
  "Jacob the Liar",
  "Jacob’s Room",
  "Jacques the Fatalist",
  "Jahrestage",
  "Jane Eyre",
  "Jazz",
  "Jealousy",
  "Joseph and His Brothers",
  "Joseph Andrews",
  "Journey to the Alcarria",
  "Journey to the Centre of the Earth",
  "Journey to the End of the Night",
  "Jude the Obscure",
  "July’s People",
  "Junkie",
  "Justine",
  "Justine",
  "Kafka on the Shore",
  "Keep the Aspidistra Flying",
  "Kidnapped",
  "Kim",
  "King Lear of the Steppes",
  "King Solomon’s Mines",
  "Kingdom of This World",
  "Kiss of the Spider Woman",
  "Kitchen",
  "Kokoro",
  "Kristin Lavransdatter",
  "La Bête Humaine",
  "La Brava",
  "La Celestina",
  "La Reine Margot",
  "Labyrinths",
  "Lady Chatterley’s Lover",
  "Lady Number Thirteen",
  "Lanark: A Life in Four Books",
  "Land",
  "Larva: Midsummer Night's Babel",
  "Last of the Mohicans",
  "Le Père Goriot",
  "Leaden Wings",
  "Legend",
  "Les Enfants Terribles",
  "Les Misérables",
  "Less Than Zero",
  "Libra",
  "Life and Death of Harriett Frean",
  "Life is a Caravanserai",
  "Life of Christ",
  "Life of Pi",
  "Life: A User’s Manual",
  "Like Life",
  "Like Water for Chocolate",
  "Little Women",
  "Living",
  "Locus Solus",
  "Lolita",
  "London Fields",
  "London Orbital",
  "Look Homeward, Angel",
  "Looking for the Possible Dance",
  "Lord Jim",
  "Lord of the Flies",
  "Lost Illusions",
  "Lost Language of Cranes",
  "Love in a Cold Climate",
  "Love in Excess",
  "Love in the Time of Cholera",
  "Love Medicine",
  "Love’s Work",
  "Loving",
  "Lucky Jim",
  "Madame Bovary",
  "Main Street",
  "Maldoror",
  "Malone Dies",
  "Man's Fate",
  "Manhattan Transfer",
  "Manon des Sources",
  "Mansfield Park",
  "Mao II",
  "Margot and the Angels",
  "Marius the Epicurean",
  "Marks of Identity",
  "Martin Chuzzlewit",
  "Martin Eden",
  "Martin Fierro",
  "Mary Barton",
  "Marya",
  "Matigari",
  "Max Havelaar",
  "Measuring the World",
  "Melmoth the Wanderer",
  "Memento Mori",
  "Memoirs of a Geisha",
  "Memoirs of a Peasant Boy",
  "Memoirs of Hadrian",
  "Memoirs of Martinus Scriblerus",
  "Memoirs of my Nervous Illness",
  "Memoirs of Rain",
  "Memory of Fire",
  "Mercier et Camier",
  "Metamorphoses",
  "Michael Kohlhaas",
  "Midaq Alley",
  "Middlemarch",
  "Middlesex",
  "Midnight’s Children",
  "Miramar",
  "Miss Lonelyhearts",
  "Miss Pettigrew Lives for a Day",
  "Moby-Dick",
  "Moll Flanders",
  "Molloy",
  "Money to Burn",
  "Money: A Suicide Note",
  "Monica",
  "Monkey: A Journey to the West",
  "Moon Palace",
  "Moscow Stations",
  "Mother",
  "Mother's Milk",
  "Mr. Vertigo",
  "Mrs. ‘Arris Goes to Paris",
  "Mrs. Dalloway",
  "Murder Must Advertise",
  "Murphy",
  "Myra Breckinridge",
  "Nadja",
  "Naked Lunch",
  "Nana",
  "Native Son",
  "Nausea",
  "Nervous Conditions",
  "Neuromancer",
  "Never Let Me Go",
  "New Grub Street",
  "News from Nowhere",
  "Night and Day",
  "Nights at the Circus",
  "Nightwood",
  "Nineteen Eighty-Four",
  "Nineteen Seventy Seven",
  "No Laughing Matter",
  "No One Writes to the Colonel",
  "None but the Brave",
  "North and South",
  "Northanger Abbey",
  "Nostromo",
  "Notes from the Underground",
  "Novel With Cocaine",
  "Nowhere Man",
  "Obabakoak",
  "Oblomovka",
  "Of Human Bondage",
  "Of Love and Shadows",
  "Of Mice and Men",
  "Old Masters",
  "Oliver Twist",
  "On Beauty",
  "On Love",
  "On the Black Hill",
  "On the Edge of Reason",
  "On the Eve",
  "On the Heights of Despair",
  "On the Road",
  "One Day in the Life of Ivan Denisovich",
  "One Flew Over the Cuckoo’s Nest",
  "One Hundred Years of Solitude",
  "One, None and a Hundred Thousand",
  "Operation Shylock",
  "Oranges Are Not the Only Fruit",
  "Orlando",
  "Ormond",
  "Oroonoko",
  "Oscar and Lucinda",
  "Our Ancestors",
  "Our Lady of Assassins",
  "Our Mutual Friend",
  "Out of Africa",
  "Pale Fire",
  "Pallieter",
  "Pamela",
  "Parade’s End",
  "Paradise of the Blind",
  "Party Going",
  "Passing",
  "Pastoralia",
  "Patterns of Childhood",
  "Pavel's Letters",
  "Pepita Jimenez",
  "Peregrine Pickle",
  "Pereira Declares: A Testimony",
  "Perfume",
  "Persuasion",
  "Petals of Blood",
  "Pharoah",
  "Phineas Finn",
  "Pierre and Jean",
  "Pilgrimage",
  "Pippi Longstocking",
  "Platero and I",
  "Platform",
  "Play It As It Lays",
  "Pluck the Bud and Destroy the Offspring",
  "Pnin",
  "Portnoy’s Complaint",
  "Possessing the Secret of Joy",
  "Possession",
  "Pricksongs and Descants",
  "Pride and Prejudice",
  "Professor Martens' Departure",
  "Professor Unrat",
  "Promise at Dawn",
  "Quartet",
  "Quartet in Autumn",
  "Queer",
  "Quicksand",
  "Quo Vadis",
  "Rabbit is Rich",
  "Rabbit Redux",
  "Rabbit, Run",
  "Ragtime",
  "Rameau’s Nephew",
  "Rameau’s Nephew",
  "Rashomon",
  "Rasselas",
  "Ratner’s Star",
  "Reasons to Live",
  "Rebecca",
  "Red Harvest",
  "Regeneration",
  "Remains of the Day",
  "Remembering Babylon",
  "Remembrance of Things Past",
  "Requiem for a Dream",
  "Retreat Without Song",
  "Return of the Native",
  "Reveries of a Solitary Walker",
  "Rickshaw Boy",
  "Rites of Passage",
  "Rituals",
  "Rob Roy",
  "Robinson Crusoe",
  "Roderick Random",
  "Romance of the Three Kingdoms",
  "Rosshalde",
  "Roxana",
  "Sabbath’s Theater",
  "Sandokan: The Tigers of Mompracem",
  "Santa Evita",
  "Saturday",
  "Saturday Night and Sunday Morning",
  "Savage Detectives",
  "Schindler’s Ark",
  "Schooling",
  "Seasons of Migrations to the North",
  "Seize the Day",
  "Self Condemned",
  "Señor Vivo and the Coca Lord",
  "Sense and Sensibility",
  "Sentimental Education",
  "Sexing the Cherry",
  "Shame",
  "She",
  "Shikasta",
  "Shirley",
  "Shroud",
  "Siddhartha",
  "Silas Marner",
  "Silence",
  "Silk",
  "Simon and the Oaks",
  "Sister Carrie",
  "Slaughterhouse Five",
  "Slow Man",
  "Small Island",
  "Small Remedies",
  "Smell of Sadness",
  "Smiley’s People",
  "Smilla’s Sense of Snow",
  "Snow",
  "So Long a Letter",
  "Solaris",
  "Soldiers of Salamis",
  "Solitude",
  "Some Experiences of an Irish R.M.",
  "Some Prefer Nettles",
  "Sometimes a Great Notion",
  "Song of Solomon",
  "Sons and Lovers",
  "Southern Seas",
  "Spring Flowers, Spring Frost",
  "Spring Torrents",
  "Sputnik Sweetheart",
  "Steppenwolf",
  "Stone Junction",
  "Story of the Eye",
  "Strait is the Gate",
  "Stranger in a Strange Land",
  "Suite Francaise",
  "Sula",
  "Summer",
  "Summer in Baden-Baden",
  "Summer Will Show",
  "Super-Cannes",
  "Surfacing",
  "Tarka the Otter",
  "Tarr",
  "Tarzan of the Apes",
  "Tender is the Night",
  "Tent of Miracles",
  "Tess of the D’Urbervilles",
  "Testament of Youth",
  "Thais",
  "Thank You, Jeeves",
  "That They May Face the Rising Sun",
  "The 120 Days of Sodom",
  "The 13 Clocks",
  "The Abbot C",
  "The Absentee",
  "The Accidental",
  "The Adventures and Misadventures of Magroll",
  "The Adventures of Augie March",
  "The Adventures of Caleb Williams",
  "The Adventures of Huckleberry Finn",
  "The Adventures of Sherlock Holmes",
  "The Adventurous Simplicissimus",
  "The Afternoon of a Writer",
  "The Age of Innocence",
  "The Albigenses",
  "The Amazing Adventures of Kavalier",
  "The Ambassadors",
  "The Apes of God",
  "The Artamonov Business",
  "The Atrocity Exhibition",
  "The Autobiography of Alice B. Toklas",
  "The Awakening",
  "The Back Room",
  "The Ballad for Georg Henig",
  "The Beautiful Mrs. Seidenman",
  "The Beautiful Room is Empty",
  "The Beggar Maid",
  "The Bell",
  "The Bell Jar",
  "The Bells of Basel",
  "The Betrothed",
  "The Big Sleep",
  "The Birds",
  "The Birds Fall Down",
  "The Bitter Glass",
  "The Black Dahlia",
  "The Black Prince",
  "The Blind Assassin",
  "The Blind Owl",
  "The Blithedale Romance",
  "The Bluest Eye",
  "The Body Artist",
  "The Bonfire of the Vanities",
  "The Book about Blanche and Marie",
  "The Book of Daniel",
  "The Book of Diquiet",
  "The Book of Evidence",
  "The Book of Illusions",
  "The Book of Laughter and Forgetting",
  "The Breast",
  "The Bridge on the Drina",
  "The Brothers Karamazov",
  "The Buddha of Suburbia",
  "The Burning Plain",
  "The Busconductor Hines",
  "The Butcher Boy",
  "The Call of the Wild",
  "The Case of Comrade Tulayev",
  "The Case of Sergeant Grischa",
  "The Case Worker",
  "The Castle",
  "The Castle of Crossed Destinies",
  "The Castle of Otranto",
  "The Catcher in the Rye",
  "The Cathedral",
  "The Cement Garden",
  "The Charterhouse of Parma",
  "The Charwoman’s Daughter",
  "The Child in Time",
  "The Child of Pleasure",
  "The Childermass",
  "The Christmas Oratorio",
  "The Cider House Rules",
  "The Clay Machine-Gun",
  "The Collector",
  "The Color Purple",
  "The Colour",
  "The Comfort of Strangers",
  "The Commandant",
  "The Conquest of New Spain",
  "The Corrections",
  "The Count of Monte-Cristo",
  "The Counterfeiters",
  "The Country Girls",
  "The Crime of Father Amado",
  "The Crow Road",
  "The Crying of Lot 49",
  "The Cubs and Other Stories",
  "The Curious Incident of the Dog in the Night-Time",
  "The Dark Child",
  "The Daugther",
  "The Dead Father",
  "The Deadbeats",
  "The Death of Artemio Cruz",
  "The Death of Ivan Ilyich",
  "The Death of Virgil",
  "The Devil and Miss Prym",
  "The Devil in the Flesh",
  "The Devil to Pay in the Backlands",
  "The Devil's Pool",
  "The Devils",
  "The Diary of Jane Somers",
  "The Discovery of Heaven",
  "The Dispossessed",
  "The Diviners",
  "The Double",
  "The Driver’s Seat",
  "The Drowned and the Saved",
  "The Drowned World",
  "The Dumas Club",
  "The Electric Kool-Aid Acid Test",
  "The Emigrants",
  "The Enchanted Wanderer",
  "The End of the Affair",
  "The End of the Road",
  "The End of the Story",
  "The Engineer of Human Souls",
  "The English Patient",
  "The Enormous Room",
  "The Fall of the House of Usher",
  "The Fan Man",
  "The Feast of the Goat",
  "The Female Quixote",
  "The First Circle",
  "The First Garden",
  "The Floating Opera",
  "The Folding Star",
  "The Forbidden Realm",
  "The Forest of the Hanged",
  "The Forsyte Sage",
  "The Fox",
  "The French Lieutenant’s Woman",
  "The Garden of the Finzi-Continis",
  "The Garden Party",
  "The Garden Where the Brass Band Played",
  "The German Lesson",
  "The Ghost Road",
  "The Girls of Slender Means",
  "The Glass Bead Game",
  "The Glass Bees",
  "The Glass Key",
  "The Glimpses of the Moon",
  "The Go-Between",
  "The God of Small Things",
  "The Godfather",
  "The Golden Ass",
  "The Golden Bowl",
  "The Golden Notebook",
  "The Good Soldier",
  "The Good Soldier Švejk",
  "The Graduate",
  "The Grapes of Wrath",
  "The Grass is Singing",
  "The Great Gatsby",
  "The Great Indian Novel",
  "The Green Hat",
  "The Green Man",
  "The Ground Beneath Her Feet",
  "The Guide",
  "The Guiltless",
  "The Hamlet",
  "The Hand of Ethelberta",
  "The Handmaid’s Tale",
  "The Harvesters",
  "The Heart of Redness",
  "The Heart of the Matter",
  "The Heat of the Day",
  "The Heather Blazing",
  "The Heretic",
  "The History of the Siege of Lisbon",
  "The Hitchhiker’s Guide to the Galaxy",
  "The Hive",
  "The Hobbit",
  "The Holder of the World",
  "The Honorary Consul",
  "The Hothouse",
  "The Hound of the Baskervilles",
  "The Hour of the Star",
  "The Hours",
  "The House by the Medlar Tree",
  "The House in Paris",
  "The House of Doctor Dee",
  "The House of Mirth",
  "The House of the Seven Gables",
  "The House of the Spirits",
  "The House on the Borderland",
  "The House with the Blind Glass Windows",
  "The Human Stain",
  "The Hunchback of Notre Dame",
  "The Idiot",
  "The Immoralist",
  "The Inferno",
  "The Information",
  "The Inheritance of Loss",
  "The Interesting Narrative",
  "The Invention of Curried Sausage",
  "The Invisible Man",
  "The Iron Heel",
  "The Island of Dr. Moreau",
  "The Joke",
  "The Judge and His Hangman",
  "The Jungle",
  "The Killer Inside Me",
  "The Kindly Ones",
  "The Kreutzer Sonata",
  "The Labyrinth of Solitude",
  "The Lambs of London",
  "The Last Chronicle of Barset",
  "The Last Days of Humanity",
  "The Last of Mr. Norris",
  "The Last September",
  "The Last Temptation of Christ",
  "The Last World",
  "The Late-Night News",
  "The Laws",
  "The Left-Handed Woman",
  "The Leopard",
  "The Life and Adventures of Nicholas Nickleby",
  "The Life and Opinions of the Tomcat Murr",
  "The Life and Times of Michael K",
  "The Life of a Good-for-Nothing",
  "The Life of Insects",
  "The Life of Lazarillo de Tormes",
  "The Light of Day",
  "The Line of Beauty",
  "The Lion of Flanders",
  "The Little Prince",
  "The Living and the Dead",
  "The Lonely Londoners",
  "The Long Dark Teatime of the Soul",
  "The Long Goodbye",
  "The Lord of the Rings",
  "The Lost Honor of Katharina Blum",
  "The Lost Steps",
  "The Lover",
  "The Lusiad",
  "The Magic Mountain",
  "The Magician of Lublin",
  "The Magus",
  "The Making of Americans",
  "The Maltese Falcon",
  "The Man of Feeling",
  "The Man Who Loved Children",
  "The Man With the Golden Arm",
  "The Man Without Qualities",
  "The Mandarins",
  "The Manila Rope",
  "The Manor",
  "The Manors of Ulloa",
  "The Marble Faun",
  "The Master",
  "The Master and Margarita",
  "The Master of Ballantrae",
  "The Master of Petersburg",
  "The Mayor of Casterbridge",
  "The Melancholy of Resistance",
  "The Midnight Examiner",
  "The Midwich Cuckoos",
  "The Mill on the Floss",
  "The Monastery",
  "The Monk",
  "The Moon and the Bonfires",
  "The Moonstone",
  "The Moor’s Last Sigh",
  "The Murder of Roger Ackroyd",
  "The Museum of Unconditional Surrender",
  "The Music of Chance",
  "The Mysteries of Udolpho",
  "The Name of the Rose",
  "The Names",
  "The Namesake",
  "The New World",
  "The New York Trilogy",
  "The Newton Letter",
  "The Nice and the Good",
  "The Nine Tailors",
  "The Nose",
  "The Notebooks of Malte Laurids Brigge",
  "The Nun",
  "The Ogre",
  "The Old Devils",
  "The Old Man and the Sea",
  "The Old Wives’ Tale",
  "The Once and Future King",
  "The Opposing Shore",
  "The Optimist's Daughter",
  "The Outsider",
  "The Parable of the Blind",
  "The Passion",
  "The Passion According to G.H.",
  "The Passion of New Eve",
  "The Path to the Nest of Spiders",
  "The People of Hemsö",
  "The Piano Teacher",
  "The Picture of Dorian Gray",
  "The Pigeon",
  "The Pilgrim’s Progress",
  "The Pit and the Pendulum",
  "The Plague",
  "The Player of Games",
  "The Plot Against America",
  "The Plumed Serpent",
  "The Poisonwood Bible",
  "The Poor Mouth",
  "The Port",
  "The Portrait of a Lady",
  "The Posthumous Memoirs of Bras Cubas",
  "The Postman Always Rings Twice",
  "The Power and the Glory",
  "The Prime of Miss Jean Brodie",
  "The Princess of Clèves",
  "The Private Memoirs and Confessions of a Justified Sinner",
  "The Professor’s House",
  "The Public Burning",
  "The Purloined Letter",
  "The Pursuit of Love",
  "The Quest",
  "The Quest for Christa T.",
  "The Quiet American",
  "The Radetzky March",
  "The Radiant Way",
  "The Ragazzi",
  "The Ragged Trousered Philanthropists",
  "The Rainbow",
  "The Ravishing of Lol V. Stein",
  "The Razor’s Edge",
  "The Reader",
  "The Real Charlotte",
  "The Rebel",
  "The Recognitions",
  "The Red and the Black",
  "The Red Queen",
  "The Red Room",
  "The Regent's Wife",
  "The Reluctant Fundamentalist",
  "The Return of Philip Latinowicz",
  "The Return of the Soldier",
  "The Revenge for Love",
  "The Riddle of the Sands",
  "The Rings of Saturn",
  "The River Between",
  "The Robber Bride",
  "The Romantics",
  "The Roots of Heaven",
  "The Safety Net",
  "The Satanic Verses",
  "The Scarlet Letter",
  "The Sea",
  "The Sea of Fertility",
  "The Sea, The Sea",
  "The Secret Agent",
  "The Secret History",
  "The Shadow Line",
  "The Shadow Lines",
  "The Shining",
  "The Shipping News",
  "The Shipyard",
  "The Siege of Krishnapur",
  "The Singapore Grip",
  "The Sorrow of Belgium",
  "The Sorrows of Young Werther",
  "The Sound and the Fury",
  "The Sound of Waves",
  "The Spy Who Came in from the Cold",
  "The Stechlin",
  "The Stone Diaries",
  "The Storm of Steel",
  "The Story of Lucy Gault",
  "The Story of O",
  "The Strange Case of Dr. Jekyll and Mr. Hyde",
  "The Street of Crocodiles",
  "The Successor",
  "The Summer Book",
  "The Sun Also Rises",
  "The Swarm",
  "The Swimming-Pool Library",
  "The Taebek Mountains",
  "The Tale of Genji",
  "The Tale of the Bamboo Cutter",
  "The Talented Mr. Ripley",
  "The Talk of the Town",
  "The Tartar Steppe",
  "The Temple of My Familiar",
  "The Temptation of Saint Anthony",
  "The Tenant of Wildfell Hall",
  "The Thin Man",
  "The Things They Carried",
  "The Thinking Reed",
  "The Third Man",
  "The Third Policeman",
  "The Third Wedding",
  "The Thirty-Nine Steps",
  "The Thousand and One Nights",
  "The Three Musketeers",
  "The Three Trapped Tigers",
  "The Time Machine",
  "The Time of Indifference",
  "The Time of the Hero",
  "The Tin Drum",
  "The Tin Flute",
  "The Travels of Persiles and Sigismunda",
  "The Tree of Man",
  "The Trial",
  "The Trick is to Keep Breathing",
  "The Triple Mirror of the Self",
  "The Trusting and the Maimed",
  "The Turn of the Screw",
  "The Twilight Years",
  "The Twins",
  "The Unbearable Lightness of Being",
  "The Unconsoled",
  "The Underdogs",
  "The Unfortunate Traveller",
  "The Unknown Soldier",
  "The Unnamable",
  "The Untouchable",
  "The Vicar of Wakefield",
  "The Vice-Consul",
  "The Viceroys",
  "The Victim",
  "The Violent Bear it Away",
  "The Virgin in the Garden",
  "The Virgin Suicides",
  "The Voyage Out",
  "The War at the End of the World",
  "The War of the Worlds",
  "The Wars",
  "The Wasp Factory",
  "The Water Margin",
  "The Water-Babies",
  "The Waves",
  "The Way of All Flesh",
  "The Well of Loneliness",
  "The Wild Boys",
  "The Wind-Up Bird Chronicle",
  "The Wings of the Dove",
  "The Witness",
  "The Woman in White",
  "The Wonderful “O”",
  "The Woodlanders",
  "The World According to Garp",
  "The Year of the Death of Ricardo Reis",
  "The Year of the Hare",
  "The Years",
  "The Yellow Wallpaper",
  "The Young Man",
  "Their Eyes Were Watching God",
  "Them",
  "Thérèse Raquin",
  "They Shoot Horses, Don’t They?",
  "Things Fall Apart",
  "Things: A Story of the Sixties",
  "This Way for the Gas, Ladies and Gentlemen",
  "Thomas of Reading",
  "Three Lives",
  "Threepenny Novel",
  "Through the Looking Glass",
  "Thursbitch",
  "Timbuktu",
  "Time of Silence",
  "Time’s Arrow",
  "Tinker Tailor Soldier Spy",
  "Tipping the Velvet",
  "Tirant lo Blanc",
  "Titus Groan",
  "To Each His Own",
  "To Have and Have Not",
  "To Kill a Mockingbird",
  "To The Lighthouse",
  "To the North",
  "Tom Jones",
  "Tono-Bungay",
  "Trainspotting",
  "Transit",
  "Trawl",
  "Treasure Island",
  "Tristram Shandy",
  "Tropic of Cancer",
  "Tropic of Capricorn",
  "Troubles",
  "Troubling Love",
  "Typical",
  "U.S.A.",
  "Ulysses",
  "Uncle Petros and Goldbach's Conjecture",
  "Uncle Silas",
  "Uncle Tom’s Cabin",
  "Under Fire",
  "Under Satan's Sun",
  "Under the Net",
  "Under the Skin",
  "Under the Volcano",
  "Under the Yoke",
  "Underworld",
  "Unless",
  "Untouchable",
  "V.",
  "Vanishing Point",
  "Vanity Fair",
  "Vathek",
  "Vernon God Little",
  "Veronika Decides to Die",
  "Vertigo",
  "Vile Bodies",
  "Villette",
  "Vineland",
  "Vipers' Tangle",
  "Virgin Soil",
  "Voss",
  "W, or the Memory of childhood",
  "Waiting for the Barbarians",
  "Waiting for the Dark, Waiting for the Light",
  "Walden",
  "War and Peace",
  "War with the Newts",
  "Watchmen",
  "Waterland",
  "Watt",
  "We",
  "What a Carve Up!",
  "What I Loved",
  "What Maisie Knew",
  "Whatever",
  "Where Angels Fear to Tread",
  "White Noise",
  "White Teeth",
  "Wide Sargasso Sea",
  "Wild Harbour",
  "Wild Swans",
  "Wilhelm Meister’s Apprenticeship",
  "Willard and His Bowling Trophies",
  "Wise Blood",
  "Wise Children",
  "Wittgenstein’s Mistress",
  "Wittgenstein’s Nephew",
  "Woman at Point Zero",
  "Women in Love",
  "World’s End",
  "Worstward Ho",
  "Written on the Body",
  "Wuthering Heights",
  "Yes",
  "Young Törless",
  "Your Face Tomorrow",
  "Youth",
  "Z",
  "Zeno’s Conscience",
  "Zorba the Greek",
  ]

  export default bookTitles;